#!/usr/bin/python3
import random
import sys

l = lambda: random.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
d = lambda: random.choice('0123456789')
codename = lambda: l() + l() + '-' + d() + d()

num = int(sys.argv[1]) if len(sys.argv) > 1 else 1
for i in range(num):
    print(codename())
